### ISSUE TITLE
Missing ZeroCycle files

### ISSUE THREAD

**Issue by lzj1769** [ren-lab/snp-selex#1]
Hi,

Thanks for making the codes publicly available.

I am trying to re-train the svm model with your codes, and I have downloaded the 7443 fastq files from https://www.ebi.ac.uk/ena/browser/view/PRJEB9797, 

but when I try to run snakemake, there is an error message saying zerocycle file is missing:

```
Building DAG of jobs...
MissingInputException in line 56 of /rwthfs/rz/cluster/hpcwork/rwth0776/snp-selex/deltasvm/Snakefile:
Missing input files for rule fastqTofasta:
fastq/ZeroCycle_TGTTAA40NACT_0_0.fastq.gz
```
so where can I download these files?

Thanks and best,
Zhijian Li

**Comment by yjqiu** [comment]
The issue has been resolved via direct commutation.
