### ISSUE TITLE
Applying 94 high-confidence model on single neucleotide mutations

### ISSUE THREAD

**Issue by WeiCSong** [ren-lab/snp-selex#2]
Hi, thanks for the great tool and resources on TF binding! I intend to use the 94 deltaSVM models to predict the effect of several de novo SNV, and i'm puzzled about the deltasvm folder. It seems that the scripts in this folder are used to train novel model (and they need the large file you mentioned in readme), and seems that the models presented in the paper are not stored here. Is there a way to directly apply your 94 model on new SNV in a way like "python model.py file_storing_SNV_sequence"? Maybe i missed it, but i failed to find similar commands in the snakefile. Thank you very much for your help!

**Comment by yjqiu** [comment]
@WeiCSong Sorry for the late reply. The tool you are looking for is in https://github.com/ren-lab/deltaSVM. This repo is for training models instead of making prediction. If you only have a handful SNV, the easier way is to use our webserver directly. http://renlab.sdsc.edu/GVATdb/
